# Site settings
title: "{ Swastik Mahapatra }"
description: This website is my personal portfolio
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://www.linkedin.com/in/swastikmahapatra/"

# User settings
username: Swastik Mahapatra
user_description: Machine Learning Engineer in Computer Vision
user_title: Senior Machine Learning Engineer
email: swastik.mhptr@gmail.com
twitter_username: SwastikMahapat8
github_username: swastikmhptr
gplus_username: swastik.mhptr

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
