# Site settings
title: "{ Abhilash K R }"
description: This website talks about myself and my works
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://abhilashkr.me"

# User settings
username: Abhilash K R
user_description: I'm a Software Developer, Data Science Enthusiast and a Coffee Addict
user_title: Software Developer / Data Science Enthusiast
email: abhilash.khokle@gmail.com
twitter_username: KhokleKr
github_username: Better-Boy
gplus_username: AbhilashKrbetterboy

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
